# Generated by Django 4.2.20 on 2025-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reapcycle",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reapcycle",
            name="start_date",
            field=models.DateField(),
        ),
    ]
