# Generated by Django 4.2.20 on 2025-05-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_reapcycle_name_alter_reapcycle_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reapuseranswer",
            old_name="is_submitted",
            new_name="is_auto_submitted",
        ),
        migrations.RenameField(
            model_name="reapuseranswer",
            old_name="reap_cycle",
            new_name="reap",
        ),
        migrations.RenameField(
            model_name="reapuseranswer",
            old_name="question",
            new_name="reap_question",
        ),
        migrations.AlterUniqueTogether(
            name="reapuseranswer",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="reapquestion",
            name="reap_cycle",
        ),
        migrations.AddField(
            model_name="reapquestion",
            name="reap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.reapcycle",
            ),
        ),
        migrations.AddField(
            model_name="reapquestion",
            name="visible_to",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("RM", "RM"),
                    ("PGM", "PGM"),
                    ("ALL", "All"),
                ],
                default="ALL",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="reapuseranswer",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reapuseranswer",
            name="is_submit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reapuseranswer",
            name="submitted_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reapcycle",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reapcycle",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reapquestion",
            name="is_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reapuseranswer",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reapuseranswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reapuseranswer",
            unique_together={("reap", "user", "reap_question", "submitted_user")},
        ),
        migrations.RemoveField(
            model_name="reapuseranswer",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="REAPUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_PENDING", "Employee Pending"),
                            ("EMPLOYEE_SUBMITTED", "Employee Submitted"),
                            ("RM_PENDING", "RM Pending"),
                            ("RM_SUBMITTED", "RM Submitted"),
                            ("PGM_PENDING", "PGM Pending"),
                            ("PGM_COMPLETED", "PGM Completed"),
                        ],
                        default="EMPLOYEE_PENDING",
                        max_length=20,
                    ),
                ),
                ("user_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("rm_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("pgm_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ctm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ctm_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pgm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pgm_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.reapcycle"
                    ),
                ),
                (
                    "rm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rm_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reap_user_mappings",
                "unique_together": {("reap", "user")},
            },
        ),
    ]
