# Generated by Django 4.2.20 on 2025-05-16 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_is_submitted_reapuseranswer_is_auto_submitted_and_more"),
    ]

    operations = []
