# Generated by Django 4.2.20 on 2025-05-19 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_auto_20250516_1312"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reapuseranswer",
            options={"ordering": ["reap_question__sequence"]},
        ),
        migrations.AlterUniqueTogether(
            name="reapuseranswer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reapusermapping",
            name="ctm_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reapuseranswer",
            name="submitted_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reapuseranswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reap_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reapusermapping",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE_PENDING", "Employee Pending"),
                    ("EMPLOYEE_SUBMITTED", "Employee Submitted"),
                    ("RM_PENDING", "RM Pending"),
                    ("RM_SUBMITTED", "RM Submitted"),
                    ("CTM_PENDING", "CTM Pending"),
                    ("CTM_SUBMITTED", "CTM Submitted"),
                    ("PGM_PENDING", "PGM Pending"),
                    ("PGM_COMPLETED", "PGM Completed"),
                ],
                default="EMPLOYEE_PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reapuseranswer",
            unique_together={("reap", "user", "submitted_user", "reap_question")},
        ),
    ]
