# Generated by Django 4.2.20 on 2025-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_ctm_submitted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reapusermapping",
            name="ctm_submitted_at",
        ),
    ]
